extends Resource
class_name Cosmetics

var armors = [
	preload("res://cosmetic_resources/armor/default_armor.tres"),
	preload("res://cosmetic_resources/armor/gold_armor.tres"),
	preload("res://cosmetic_resources/armor/pride_2_armor.tres"),
	preload("res://cosmetic_resources/armor/pride_armor.tres"),
	preload("res://cosmetic_resources/armor/green_armor.tres"),
	preload("res://cosmetic_resources/armor/purple_armor.tres"),
	preload("res://cosmetic_resources/armor/yellow_2_armor.tres"),
	preload("res://cosmetic_resources/armor/yellow_armor.tres"),
	preload("res://cosmetic_resources/armor/red_armor.tres"),
	preload("res://cosmetic_resources/armor/brown_armor.tres"),
	preload("res://cosmetic_resources/armor/white_armor.tres"),
	preload("res://cosmetic_resources/armor/grey_armor.tres"),
	preload("res://cosmetic_resources/armor/space_armor.tres"),
	preload("res://cosmetic_resources/armor/lilac_armor.tres"),
	preload("res://cosmetic_resources/armor/poke_armor.tres"),
	preload("res://cosmetic_resources/armor/undies_armor.tres"),
	preload("res://cosmetic_resources/armor/wes_armor.tres"),
	preload("res://cosmetic_resources/armor/frog_armor.tres"),
	preload("res://cosmetic_resources/armor/bart_armor.tres"),
	preload("res://cosmetic_resources/armor/sand_armor.tres"),
	preload("res://cosmetic_resources/armor/lava_armor.tres"),
	preload("res://cosmetic_resources/armor/lava_2_armor.tres"),
	preload("res://cosmetic_resources/armor/lava_3_armor.tres"),
	preload("res://cosmetic_resources/armor/upper_armor.tres"),
	preload("res://cosmetic_resources/armor/lower_armor.tres"),
	preload("res://cosmetic_resources/armor/hidden_armor.tres"),
	preload("res://cosmetic_resources/armor/inverted_armor.tres"),
	preload("res://cosmetic_resources/armor/toilet_armor.tres"),
	preload("res://cosmetic_resources/armor/bish_armor.tres"),
	preload("res://cosmetic_resources/armor/santa_1_armor.tres"),
	preload("res://cosmetic_resources/armor/twilight_armor.tres"),
	preload("res://cosmetic_resources/armor/sashimi_armor.tres"),
	preload("res://cosmetic_resources/armor/arcane_armor.tres"),
	preload("res://cosmetic_resources/armor/rust_armor.tres"),
	preload("res://cosmetic_resources/armor/slime_armor.tres"),
	preload("res://cosmetic_resources/armor/forest_armor.tres"),
	#preload("res://cosmetic_resources/armor/monkey_armor.tres"),
	#preload("res://cosmetic_resources/armor/ballen_armor.tres"),
]


